# Generated by Django 3.2 on 2022-01-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211223_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_day',
            field=models.CharField(max_length=10),
        ),
    ]
