# Generated by Django 3.2 on 2021-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20211210_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='sesh_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='content',
            new_name='sesh_notes',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='time',
            new_name='sesh_timeblock',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AddField(
            model_name='session',
            name='sesh_helptype',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
