# Generated by Django 3.2 on 2021-12-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20211210_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sesh_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sesh_helptype',
            new_name='helptype',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sesh_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sesh_timeblock',
            new_name='timeblock',
        ),
    ]
