# Generated by Django 3.2 on 2021-12-10 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20211210_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='timeblock',
            field=models.CharField(choices=[('1', '8:00-8:20'), ('2', '8:20-8:40'), ('3', '8:40-9:00'), ('4', '9:00-9:20'), ('5', '9:20-9:40'), ('6', '9:40-10:00')], default='1', max_length=10),
        ),
    ]
