# Generated by Django 3.2 on 2021-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20211210_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='timeblock',
            field=models.CharField(choices=[('1', '8:00-8:20'), ('2', '8:20-8:40'), ('3', '8:40-9:00'), ('4', '9:00-9:20'), ('5', '9:20-9:40'), ('6', '9:40-10:00')], max_length=10),
        ),
    ]
