# Generated by Django 3.2 on 2021-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20211212_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeblock',
            field=models.CharField(choices=[('8:00-8:20', '8:00-8:20'), ('8:20-8:40', '8:20-8:40'), ('8:40-9:00', '8:40-9:00'), ('9:00-9:20', '9:00-9:20'), ('9:20-9:40', '9:20-9:40'), ('9:40-10:00', '9:40-10:00')], max_length=10),
        ),
    ]
