# Generated by Django 3.2.9 on 2021-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_session_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
