# Generated by Django 3.2 on 2021-12-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_teacher_assigned_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
