# Generated by Django 3.2.9 on 2021-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='weekday',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
