# Generated by Django 3.2 on 2022-01-10 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20220104_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayblock',
            name='date_today',
        ),
        migrations.RemoveField(
            model_name='session',
            name='weekday',
        ),
        migrations.AddField(
            model_name='dayblock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
