# Generated by Django 3.2 on 2022-01-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20220110_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='session',
            name='course_teacher',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='helptype',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
